### PR TITLE
Enabling Linux aarch64 builds

### PR DESCRIPTION
**Pull request by zcobell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pull request enables builds on the Linux aarch64 architecture, see #58.

### CODE REVIEW

**Comment by zcobell** [comment]
@conda-forge-admin, please rerender

**Comment by zcobell** [comment]
Hi all - This looks ready for review. Thanks!

**Comment by iainrussell** [comment]
Thanks @zcobell! It looks like it's still not building on aarch64 though, for some reason (looking at the checks).

**Comment by zcobell** [comment]
It looks like it did, but over on Travis instead of Azure. I'll take a look and see if I can get it to go over on Azure instead if you'd like.

**Comment by iainrussell** [comment]
Interesting... would be nice to have all builds in the same place. Perhaps look here for inspiration? https://github.com/conda-forge/eccodes-feedstock/blob/main/conda-forge.yml

**Comment by zcobell** [comment]
@conda-forge-admin, please rerender

**Comment by zcobell** [comment]
Thanks for the reference @iainrussell. That was easy enough!

**Comment by zcobell** [comment]
Looks to be mostly working. Should be able to confirm when I get back into the office tomorrow. It looks to me that the aarch64 builds take an incredibly long time on Azure (3.5 hours and counting) which probably means they're running through an emulator whereas Travis was doing it natively and the times were more reasonable. Since these builds don't happen every day, I defer to you if you'd like to put it back to Travis or leave it on Azure.

**Comment by zcobell** [comment]
Well, unfortunately the (assumed) emulation issues on Azure eventually did time out. @iainrussell - are you good with doing the ARM builds @ Travis?

**Comment by zcobell** [comment]
@conda-forge-admin, please rerender

**Comment by zcobell** [comment]
@iainrussell - I've re-configured so that it uses Travis for the Linux ARM builds and everything ran smoothly.

**Comment by zcobell** [comment]
Hi @iainrussell - just wanted to follow up on this. Thanks!

**Comment by zcobell** [comment]
@conda-forge-admin, please rerender

**Comment by iainrussell** [comment]
Hi @zcobell, so sorry for the slowness to respond! Yes, thanks for reverting back to Travis for this one - it seems that Azure always timed out. It's all working now, so I will merge this. Many thanks!
Iain

**Comment by zcobell** [comment]
Thank you @iainrussell! This will be a tremendous help running on our ecflow based systems on inexpensive cloud computing platforms. And no worries on the slowness at all, I'm guilty of the same often as well.

**Comment by iainrussell** [comment]
Thanks for your understanding, I wish you all the best!

**Pull request merged**
