### PR TITLE
Version 5.3.1

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by iainrussell** [comment]
@conda-forge-admin, please rerender

**Comment by iainrussell** [comment]
The third day in a row that we've uploaded tarballs and conda-forge has not detected them!

**Comment by dtip** [comment]
@ocefpaf any idea why the auto-update bot wouldn't be picking up these ECMWF packages?

ecflow: released 16 hours ago
metview: new release not noticed after 24 hours https://github.com/conda-forge/metview-feedstock/pull/25
magics: new released not noticed after at least 24 hours https://github.com/conda-forge/magics-feedstock/pull/67

Do we need to give it a bit more time to find the tarballs?

**Comment by ocefpaf** [comment]
> @ocefpaf any idea why the auto-update bot wouldn't be picking up these ECMWF packages?

16 hours is enough. The URL did not change and the `jinja` here is not problematic :-/

@beckermr any idea if recent changes broke recipes like this one?

**Comment by beckermr** [comment]
It looks like the bot could not find the new version. I am not sure why.

**Comment by dtip** [comment]
@beckermr & @ocefpaf thanks for investigating! Could you link to the logs so I can dig a little?

@iainrussell Could there be some sort of anti-DDOS or anti-scraper behaviour on confluence which is blocking the conda forge bot?

**Comment by beckermr** [comment]
We don't have logs for exactly what failed.

**Comment by iainrussell** [comment]
@dtip - interesting question, I was also thinking there might be something on our side that prevents this sort of behaviour! I didn't consider it very seriously, since the system has worked in the fairly recent past, but I'll check with the appropriate people now.

**Comment by dtip** [comment]
Perhaps with all the ECMWF feedstocks we've been adding recently the bot crossed some threshold and got itself blocked!

**Comment by beckermr** [comment]
Ahhhhhhhhhh. here is the issue

```
In [1]: from conda_forge_tick.update_upstream_versions import next_version                                                                                                

In [2]: for v in next_version("5.2.3"): 
   ...:     print(v) 
   ...:                                                                                                                                                                   
5.2.4
5.3.0
6.0.0
```

The version bump here was in a range the bot simply doesn't check.

**Comment by beckermr** [comment]
Don't bump in odd ways and we can find it! ;p

**Comment by dtip** [comment]
Any ideas about the other two? Metview went from v5.8.2 to v5.8.3. Magics went from v4.3.0 to v4.3.1. Both seem like reasonable bumps!

**Comment by beckermr** [comment]
I will look at those! Can you open an issue on regro/cf-scripts for me to check. I don't have time right now

**Comment by dtip** [comment]
Done https://github.com/regro/cf-scripts/issues/942

**Pull request merged**
