### PR TITLE
Update project documentation URL in Conda recipe

### PR DESCRIPTION
**Pull request by kinow**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Hello,

This PR can be left without merging until maintainers want to cut a new release, if they prefer. It is just a reminder to update the project documentation URL in this Conda recipe :+1: 

Thanks
Bruno

### CODE REVIEW

**Comment by iainrussell** [comment]
That's great @kinow - thank you!

**Comment by kinow** [comment]
> That's great @kinow - thank you!

Hi @iainrussell ,

I think I forgot to ask the bot to re-render the recipe files, so the readme file is still using the old URL (I can't recall exactly, but I think that's how that URL is first generated?). Let me know if you'd like me to send another PR. Otherwise in the next release I believe that will use the new URL anyway :+1: 

Thank you!

**Comment by iainrussell** [comment]
Hi @kinow, that's fine, we expect to make a small new release in the next couple of days, so the readme should be updated then.

**Comment by kinow** [comment]
Perfect. Thank you @iainrussell !

**Pull request merged**
