### PR TITLE
Enabling Linux aarch64 builds

### PR DESCRIPTION
**Pull request by zcobell**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This pull request enables builds on the Linux aarch64 architecture, see #58.

### CODE REVIEW

**Comment by zcobell** [comment]
@conda-forge-admin, please rerender

**Comment by zcobell** [comment]
Note this appears to be failing because the CI system is having trouble getting to https://confluence.ecmwf.int this morning (as am I). Looks like it will just need to be restarted once the site comes back up.

**Comment by iainrussell** [comment]
The current failures here are because we have a power outage on the machine that hosts the ecFlow source at the moment...

**Comment by zcobell** [comment]
Thanks @iainrussell for confirming!

**Comment by zcobell** [comment]
Closing this and starting fresh in a new PR now that the servers have returned to service

**Pull request closed without merging**
